### PR TITLE
DI-706 v3.1.0

### PR DESCRIPTION
**Pull request by rklocke**
**Note:** There are too many changes for GitHub to recognise the JSON as the same file after renaming (no pretty diff) so I created a branch (_DI-706_v3.1.0_) to rename the JSON then branched from there to make changes  (_v3.1.0_changes_) - the DI-706_v3.1.0 branch will be merged to main later once everything is finalised.

**Changes**
- Rename file from v3.0.2 -> 3.1.0
- Update version in file v3.0.2 -> 3.1.0
- Add `artemis_app_id` (v1.4.0) `app-GfKV5204ZF35Z47z31Qzqx90`
- Update genepanels and g2t file IDs to newer versions
- Update SNV reports workflow to v2.2.0

- **snv_reports**
  - Update input names for eggd_generate_bed (exons_nirvana -> exons and nirvana_genes2transcripts -> genes2transcripts) which affects:
    - stage-rpt_generate_bed_athena 
    - stage-rpt_generate_bed_vep
  - Add new string inputs which work with new eggd_dias_batch (v3.1.0) which affects:
     - stage-rpt_generate_bed_athena
     - stage-rpt_generate_bed_vep
     - stage-rpt_generate_workbook
     - stage-rpt_athena
  - **stage-rpt_vep**
    - Update config file ID for new version `twe_vep_config_v1.1.13.json`
  - Add inputs for new app eggd_optimised_filtering
  - **stage-rpt_generate_workbook**
     - Remove `CSQ_gnomADg_AF_popmax` and `CSQ_gnomADe_AF_popmax` from `exclude_columns` because they're now used for filtering
     - Update `acmg` from true -> 3
     - Update `filter` to just filter out EXCLUDE variants since filtering now done within eggd_optimised_filtering
     - Update `human_filter` to reflect new filtering
     - Update `reorder_columns` to include  `CSQ_gnomADg_AF_popmax`, `CSQ_gnomADe_AF_popmax` and `MOI`
     - Add new input `lock_sheet` set to true
  - **stage-rpt_athena**
    - Add new input `indication`
- **eggd_artemis**
  - Add inputs since now being used for TWE

- **README**
  - Update title dias_TWE_config_GRCh37_v3.0.2.json -> dias_TWE_config_GRCh37_v3.1.0.json
  - Correct typo egg5_dias_TWE_config -> egg4_dias_TWE_config
  - Update Dias reports version dias_reports_v2.1.0 → dias_reports_v2.2.0
  - Update Dias reports workflow ID `workflow-GXzkfYj4QPQp9z4Jz4BF09y6` → `workflow-Gg9Yvj04z4VvPFF3fygp63jy`
  - Update dynamic files genepanels, genes2transcripts and twe_vep_config file names and IDs

**Testing**
The config was uploaded to DNAnexus (https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/data/?scope=project&id.values=file-GgFf5k04z4Vkjz3zJ6kYpGPf) and used as an input to eggd_dias_batch v3.1.0 to run SNV reports and artemis for two TWE samples:
**Dias batch job**:
https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/monitor/job/GgFf8pj4z4Vb01XYYvP7Q26ZGgF093j4z4Vk6GgkkkbVy62q
**SNV reports jobs:**
- https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/monitor/analysis/GgFf9804z4Vz7Xgv88pQx6Pg
- https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/monitor/analysis/GgFf9884z4VjfzVv8Jf1Bq8y

**Artemis:**
https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/monitor/job/GgFf98j4z4VbGJQX5X7z7BPP

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47)

### CODE REVIEW

**Comment by rklocke** [comment]
Converted to draft - new VEP config will now be added to this update as well

**Review by Addy81 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47)* status: 1 of 2 files reviewed, 9 unresolved discussions (waiting on @chrispyatt, @kjwinfield, and @rklocke)

___
*[`dias_TWE_config_GRCh37_v3.1.0.json` line 49 at r2](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47#-NrGSVGCCY6Gy1s9VfNE:-NrGSVGCCY6Gy1s9VfNF:b4xuhwa) ([raw file](https://github.com/eastgenomics/egg4_dias_TWE_config/blob/4c3ef0f6b23e9125b5d8e4cdee7cecd61551f7c4/dias_TWE_config_GRCh37_v3.1.0.json#L49)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-Gg35Vf845B5bV08VqJ0qGV5V"
> ```

240202_panelapp_dump.json :lgtm_strong: 
___
*[`dias_TWE_config_GRCh37_v3.1.0.json` line 56 at r2](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47#-NrGS_mD27XeN8AhHVeq:-NrGS_mD27XeN8AhHVer:bcwlzk3) ([raw file](https://github.com/eastgenomics/egg4_dias_TWE_config/blob/4c3ef0f6b23e9125b5d8e4cdee7cecd61551f7c4/dias_TWE_config_GRCh37_v3.1.0.json#L56)):*
> ```JSON
>                 "stage-rpt_generate_workbook.output_prefix": "INPUT-sample_name",
>                 "stage-rpt_generate_workbook.exclude_columns": "BaseQRankSum ClippingRankSum DB ExcessHet FS MLEAC MLEAF MQ MQRankSum QD ReadPosRankSum SOR PL QUAL ID FILTER  CSQ_ClinVar_CLNSIGCONF  CSQ_Allele CSQ_HGNC_ID DP AC AF AN CSQ_SpliceAI_pred_DP_AL CSQ_SpliceAI_pred_DP_AG CSQ_SpliceAI_pred_DP_DG CSQ_SpliceAI_pred_DP_DL CSQ_gnomADe_AC_popmax CSQ_gnomADe_AN_popmax CSQ_gnomADe_nhomalt_popmax CSQ_gnomADe_non_cancer_AC CSQ_gnomADe_non_cancer_AC_popmax CSQ_gnomADe_non_cancer_AF CSQ_gnomADe_non_cancer_AF_popmax CSQ_gnomADe_non_cancer_AN CSQ_gnomADe_non_cancer_AN_popmax CSQ_gnomADe_non_cancer_nhomalt CSQ_gnomADe_non_cancer_nhomalt_popmax CSQ_gnomADe_non_cancer_popmax CSQ_gnomADe_popmax CSQ_gnomADg_AC_popmax CSQ_gnomADg_AN_popmax CSQ_gnomADg_nhomalt_popmax CSQ_gnomADg_popmax",
>                 "stage-rpt_generate_workbook.acmg": 3,
> ```

:lgtm_strong: discussed this in meeting, chose 3 as the acmg table is now locked and it is unlikely to need more than 3
___
*[`dias_TWE_config_GRCh37_v3.1.0.json` line 83 at r2](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47#-NrGTFdLB1SLqPal9o9v:-NrGTFdLB1SLqPal9o9w:bymz94e) ([raw file](https://github.com/eastgenomics/egg4_dias_TWE_config/blob/4c3ef0f6b23e9125b5d8e4cdee7cecd61551f7c4/dias_TWE_config_GRCh37_v3.1.0.json#L83)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-GFPxpJj4GVV0Pfzv4VGYf1pq"
> ```

CEN capture bed,c ould it be replaced with a TWE bed file?
___
*[`README.md` line 20 at r2](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47#-NrGTxwiEeVwAPT22RLz:-NrGTxwiEeVwAPT22RM-:bb47ufi) ([raw file](https://github.com/eastgenomics/egg4_dias_TWE_config/blob/4c3ef0f6b23e9125b5d8e4cdee7cecd61551f7c4/README.md#L20)):*
> ```Markdown
>     * DNAnexus workflow ID: `workflow-Gg9Yvj04z4VvPFF3fygp63jy`
> 
> Dynamic files:
> ```

can you add the panel dump in this list?

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Addy81, @chrispyatt, and @kjwinfield)

___
*[`dias_TWE_config_GRCh37_v3.1.0.json` line 43 at r2](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47#-NrGYrapDi1LSZzta-wF:-NrGoGYwCFDI087khbBe:bralv5u) ([raw file](https://github.com/eastgenomics/egg4_dias_TWE_config/blob/4c3ef0f6b23e9125b5d8e4cdee7cecd61551f7c4/dias_TWE_config_GRCh37_v3.1.0.json#L43)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

should the !~ near the start of this be escaped?
</blockquote></details>

So JSON doesn't seem to like escaping a ! char, in the current batch config the ! in the bcftools filter is not escaped - is this fine?
___
*[`dias_TWE_config_GRCh37_v3.1.0.json` line 83 at r2](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47#-NrGTFdLB1SLqPal9o9v:-NrGok9_93G4XLf2zAgV:bb6un1j) ([raw file](https://github.com/eastgenomics/egg4_dias_TWE_config/blob/4c3ef0f6b23e9125b5d8e4cdee7cecd61551f7c4/dias_TWE_config_GRCh37_v3.1.0.json#L83)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

CEN capture bed,c ould it be replaced with a TWE bed file?
</blockquote></details>

Done
___
*[`README.md` line 20 at r2](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47#-NrGTxwiEeVwAPT22RLz:-NrGoqS90Zfbp7CfCVUz:bb6un1j) ([raw file](https://github.com/eastgenomics/egg4_dias_TWE_config/blob/4c3ef0f6b23e9125b5d8e4cdee7cecd61551f7c4/README.md#L20)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

can you add the panel dump in this list?
</blockquote></details>

Done

**Comment by rklocke** [comment]
To check if it's an issue not having an escape before a '!' char in the config for the bcftools filter string, I re-ran an eggd_optimised_filtering job for the same sample as before:

Original eggd_optimised_filtering job in reports workflow using unescaped '!' in bcftools filter command in batch config:
https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/monitor/job/GgFf9884z4VjfzVv8Jf1Bq93/try/0

New eggd_optimised_filtering job for the same sample and parameters but using escaped bcftools filter command:
```
newfilter="bcftools filter --soft-filter \"EXCLUDE\" -m + -e '(CSQ_ClinVar_CLNSIGCONF\!~ \"pathogenic\\/i\" & CSQ_HGMD_CLASS!= \"DM\" & CSQ_ClinVar_CLNSIG!=\"Pathogenic\\/i\" & CSQ_ClinVar_CLNSIG!=\"Likely pathogenic\\/i\") & (((MOI=\"AR\" | MOI=\"AD/AR\" | MOI=\"XLR\" | MOI=\"XLD\" | MOI=\"MITOCHONDRIAL\" | MOI=\"UNKNOWN\" | MOI=\"OTHER\" | MOI=\"NONE\") & (CSQ_gnomADg_AF>0.01 | CSQ_gnomADe_AF>0.01)) | (MOI=\"AD\" & (CSQ_gnomADg_AF>0.001 |CSQ_gnomADe_AF>0.001)) | CSQ_TWE_AF>0.05 | ((CSQ_Consequence=\"synonymous_variant\" | CSQ_Consequence=\"intron_variant\" | CSQ_Consequence=\"upstream_gene_variant\" | CSQ_Consequence=\"downstream_gene_variant\" | CSQ_Consequence=\"intergenic_variant\" | CSQ_Consequence=\"5_prime_UTR_variant\" | CSQ_Consequence=\"3_prime_UTR_variant\") & CSQ_HGMD_CLASS!= \"DM?\"))'"
dx run eggd_optimised_filtering -iinput_vcf=file-GgFfXvj4ff9p40PV0zQ4FPjb -ifilter_string="$newfilter" -ipanel_string='R147.1_Growth failure in early childhood_P' -igenepanels='project-Fkb6Gkj433GVVvj73J7x8KbV:file-GgBG75Q433Gk4pY5qpxbgVyz' -ipanel_dump='project-Fkb6Gkj433GVVvj73J7x8KbV:file-Gg35Vf845B5bV08VqJ0qGV5V' --name "240223_test_bcftools_filter_escape"
```
Job: https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/monitor/job/GgG702Q4z4VfbBXV296bxVf1

Compare outputs:
```
diff <(dx cat file-GgFfYX84K9qPyK168k6y452P | zcat) <(dx cat file-GgG71X847ZfG77pG5p150fy6 | zcat)
240c240
< ##bcftools_split-vepCommand=split-vep --columns - -a CSQ -Ou -p CSQ_ -d /home/dnanexus/in/input_vcf/123230469-23145R0145-23NGWES6-9526-F-103698_markdup_recalibrated_Haplotyper_annotated.vcf.gz; Date=Thu Feb 22 15:35:36 2024
---
> ##bcftools_split-vepCommand=split-vep --columns - -a CSQ -Ou -p CSQ_ -d /home/dnanexus/in/input_vcf/123230469-23145R0145-23NGWES6-9526-F-103698_markdup_recalibrated_Haplotyper_annotated.vcf.gz; Date=Fri Feb 23 10:17:44 2024
242c242
< ##bcftools_annotateCommand=annotate -x INFO/CSQ -o 123230469-23145R0145-23NGWES6-9526-F-103698_markdup_recalibrated_Haplotyper_annotated.split.vcf; Date=Thu Feb 22 15:35:36 2024
---
> ##bcftools_annotateCommand=annotate -x INFO/CSQ -o 123230469-23145R0145-23NGWES6-9526-F-103698_markdup_recalibrated_Haplotyper_annotated.split.vcf; Date=Fri Feb 23 10:17:44 2024
246c246
< ##bcftools_filterCommand=filter --soft-filter EXCLUDE -m + -e '(CSQ_ClinVar_CLNSIGCONF!~ "pathogenic\/i" & CSQ_HGMD_CLASS!= "DM" & CSQ_ClinVar_CLNSIG!="Pathogenic\/i" & CSQ_ClinVar_CLNSIG!="Likely pathogenic\/i") & (((MOI="AR" | MOI="AD/AR" | MOI="XLR" | MOI="XLD" | MOI="MITOCHONDRIAL" | MOI="UNKNOWN" | MOI="OTHER" | MOI="NONE") & (CSQ_gnomADg_AF>0.01 | CSQ_gnomADe_AF>0.01)) | (MOI="AD" & (CSQ_gnomADg_AF>0.001 |CSQ_gnomADe_AF>0.001)) | CSQ_TWE_AF>0.05 | ((CSQ_Consequence="synonymous_variant" | CSQ_Consequence="intron_variant" | CSQ_Consequence="upstream_gene_variant" | CSQ_Consequence="downstream_gene_variant" | CSQ_Consequence="intergenic_variant" | CSQ_Consequence="5_prime_UTR_variant" | CSQ_Consequence="3_prime_UTR_variant") & CSQ_HGMD_CLASS!= "DM?"))' -o 123230469-23145R0145-23NGWES6-9526-F-103698_markdup_recalibrated_Haplotyper_annotated.optimised_filtered.vcf 123230469-23145R0145-23NGWES6-9526-F-103698_markdup_recalibrated_Haplotyper_annotated.sorted.vcf; Date=Thu Feb 22 15:35:36 2024
---
> ##bcftools_filterCommand=filter --soft-filter EXCLUDE -m + -e '(CSQ_ClinVar_CLNSIGCONF!~ "pathogenic\/i" & CSQ_HGMD_CLASS!= "DM" & CSQ_ClinVar_CLNSIG!="Pathogenic\/i" & CSQ_ClinVar_CLNSIG!="Likely pathogenic\/i") & (((MOI="AR" | MOI="AD/AR" | MOI="XLR" | MOI="XLD" | MOI="MITOCHONDRIAL" | MOI="UNKNOWN" | MOI="OTHER" | MOI="NONE") & (CSQ_gnomADg_AF>0.01 | CSQ_gnomADe_AF>0.01)) | (MOI="AD" & (CSQ_gnomADg_AF>0.001 |CSQ_gnomADe_AF>0.001)) | CSQ_TWE_AF>0.05 | ((CSQ_Consequence="synonymous_variant" | CSQ_Consequence="intron_variant" | CSQ_Consequence="upstream_gene_variant" | CSQ_Consequence="downstream_gene_variant" | CSQ_Consequence="intergenic_variant" | CSQ_Consequence="5_prime_UTR_variant" | CSQ_Consequence="3_prime_UTR_variant") & CSQ_HGMD_CLASS!= "DM?"))' -o 123230469-23145R0145-23NGWES6-9526-F-103698_markdup_recalibrated_Haplotyper_annotated.optimised_filtered.vcf 123230469-23145R0145-23NGWES6-9526-F-103698_markdup_recalibrated_Haplotyper_annotated.sorted.vcf; Date=Fri Feb 23 10:17:44 2024
```

Only differences are timestamps

**Review by jethror1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Addy81, @chrispyatt, and @kjwinfield)

___
*[`dias_TWE_config_GRCh37_v3.1.0.json` line 43 at r2](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47#-NrGYrapDi1LSZzta-wF:-NrKs2LVEqqoh40ymLcJ:b7a5vtt) ([raw file](https://github.com/eastgenomics/egg4_dias_TWE_config/blob/4c3ef0f6b23e9125b5d8e4cdee7cecd61551f7c4/dias_TWE_config_GRCh37_v3.1.0.json#L43)):*
if you want to escape ! in JSON it needs to be formatted as `\\!`, but I don't think it is needed here.

@chrispyatt I think what you're thinking of is the bash history substitution where you need to do `set +H` first to  turn it off or escape, else you get an error like:
```
$ bcftools filter -e "CSQ_ClinVar_CLNSIG!~\"Pathogenic\\/i\"
"  bed_test.vcf 
bash: !~\: event not found
```

This doesn't happen when using a subshell with Python subprocess like the app does:
```
>>> subprocess.run("bcftools filter -e 'CSQ_ClinVar_CLNSIG!~\"Pathogenic\\/i\"' bed_test.vcf", shell=Tru
e)
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=20231216
##source=Pisces 5.2.11.63
```

This is because when `shell=True` on POSIX systems it defaults to using `/bin/sh` (instead of bash), and does not have set built in to it that raises the error, and this can be tested by dropping into a non-Bash shell:

```
$ sh
$ bcftools filter -e "CSQ_ClinVar_CLNSIG!=\"Pathogenic\\/i\""  bed_test.vcf | head -n1
##fileformat=VCFv4.1
$ 
```

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47)* status: all files reviewed, 1 unresolved discussion (waiting on @chrispyatt)

**Review by chrispyatt — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/47)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
