### PR TITLE
Updated to use latest twe vep config v1.1.11

### PR DESCRIPTION
**Pull request by growland2**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/45)

### CODE REVIEW

**Review by kjwinfield — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/45)* status: all files reviewed, 2 unresolved discussions (waiting on @growland2)

___
*[`README.md` line 8 at r1](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/45#-Nm5Y9um9X-VIUKWJi7-:-Nm5Y9um9X-VIUKWJi70:b-5t9z63) ([raw file](https://github.com/eastgenomics/egg4_dias_TWE_config/blob/ddbeaa71dcba9aade574cba7812b1dc9fdf71ba2/README.md#L8)):*
> ```Markdown
> > When new eggd_dias_batch goes live the python script will be deleted
> 
> # dias_TWE_config_GRCh37_v3.0.0.json
> ```

update to v3.0.1
___
*[`egg4_config_v2.1.6.py` line 2 at r1](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/45#-Nm5Y4613l2MdCLi3tf8:-Nm5Y4613l2MdCLi3tf9:bhwl2l0) ([raw file](https://github.com/eastgenomics/egg4_dias_TWE_config/blob/ddbeaa71dcba9aade574cba7812b1dc9fdf71ba2/egg4_config_v2.1.6.py#L2)):*
> ```Python
> assay_name = "TWE" # Twist Whole Exome
> assay_version = "v2.1.5"
> ```

can you update this to v2.1.6?

**Review by growland2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/45)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @kjwinfield)

___
*[`README.md` line 8 at r1](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/45#-Nm5Y9um9X-VIUKWJi7-:-Nm5ZvuOEl_5raHwR2uC:b-896fix) ([raw file](https://github.com/eastgenomics/egg4_dias_TWE_config/blob/ddbeaa71dcba9aade574cba7812b1dc9fdf71ba2/README.md#L8)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

update to v3.0.1
</blockquote></details>

Done.
___
*[`egg4_config_v2.1.6.py` line 2 at r1](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/45#-Nm5Y4613l2MdCLi3tf8:-Nm5Zxfi48cn9OM3D1cH:b-896fix) ([raw file](https://github.com/eastgenomics/egg4_dias_TWE_config/blob/ddbeaa71dcba9aade574cba7812b1dc9fdf71ba2/egg4_config_v2.1.6.py#L2)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

can you update this to v2.1.6?
</blockquote></details>

Done.

**Review by kjwinfield — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/45)* status: all files reviewed, 2 unresolved discussions (waiting on @growland2)

**Review by kjwinfield — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg4_dias_TWE_config/45)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @growland2)

**Pull request merged**
